# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

schema:
  date: str
  key: str
  search_trends_abdominal_obesity: float
  search_trends_abdominal_pain: float
  search_trends_acne: float
  search_trends_actinic_keratosis: float
  search_trends_acute_bronchitis: float
  search_trends_adrenal_crisis: float
  search_trends_ageusia: float
  search_trends_alcoholism: float
  search_trends_allergic_conjunctivitis: float
  search_trends_allergy: float
  search_trends_amblyopia: float
  search_trends_amenorrhea: float
  search_trends_amnesia: float
  search_trends_anal_fissure: float
  search_trends_anaphylaxis: float
  search_trends_anemia: float
  search_trends_angina_pectoris: float
  search_trends_angioedema: float
  search_trends_angular_cheilitis: float
  search_trends_anosmia: float
  search_trends_anxiety: float
  search_trends_aphasia: float
  search_trends_aphonia: float
  search_trends_apnea: float
  search_trends_arthralgia: float
  search_trends_arthritis: float
  search_trends_ascites: float
  search_trends_asperger_syndrome: float
  search_trends_asphyxia: float
  search_trends_asthma: float
  search_trends_astigmatism: float
  search_trends_ataxia: float
  search_trends_atheroma: float
  search_trends_attention_deficit_hyperactivity_disorder: float
  search_trends_auditory_hallucination: float
  search_trends_autoimmune_disease: float
  search_trends_avoidant_personality_disorder: float
  search_trends_back_pain: float
  search_trends_bacterial_vaginosis: float
  search_trends_balance_disorder: float
  search_trends_beaus_lines: float
  search_trends_bells_palsy: float
  search_trends_biliary_colic: float
  search_trends_binge_eating: float
  search_trends_bleeding: float
  search_trends_bleeding_on_probing: float
  search_trends_blepharospasm: float
  search_trends_bloating: float
  search_trends_blood_in_stool: float
  search_trends_blurred_vision: float
  search_trends_blushing: float
  search_trends_boil: float
  search_trends_bone_fracture: float
  search_trends_bone_tumor: float
  search_trends_bowel_obstruction: float
  search_trends_bradycardia: float
  search_trends_braxton_hicks_contractions: float
  search_trends_breakthrough_bleeding: float
  search_trends_breast_pain: float
  search_trends_bronchitis: float
  search_trends_bruise: float
  search_trends_bruxism: float
  search_trends_bunion: float
  search_trends_burn: float
  search_trends_burning_chest_pain: float
  search_trends_burning_mouth_syndrome: float
  search_trends_candidiasis: float
  search_trends_canker_sore: float
  search_trends_cardiac_arrest: float
  search_trends_carpal_tunnel_syndrome: float
  search_trends_cataplexy: float
  search_trends_cataract: float
  search_trends_chancre: float
  search_trends_cheilitis: float
  search_trends_chest_pain: float
  search_trends_chills: float
  search_trends_chorea: float
  search_trends_chronic_pain: float
  search_trends_cirrhosis: float
  search_trends_cleft_lip_and_cleft_palate: float
  search_trends_clouding_of_consciousness: float
  search_trends_cluster_headache: float
  search_trends_colitis: float
  search_trends_coma: float
  search_trends_common_cold: float
  search_trends_compulsive_behavior: float
  search_trends_compulsive_hoarding: float
  search_trends_confusion: float
  search_trends_congenital_heart_defect: float
  search_trends_conjunctivitis: float
  search_trends_constipation: float
  search_trends_convulsion: float
  search_trends_cough: float
  search_trends_crackles: float
  search_trends_cramp: float
  search_trends_crepitus: float
  search_trends_croup: float
  search_trends_cyanosis: float
  search_trends_dandruff: float
  search_trends_delayed_onset_muscle_soreness: float
  search_trends_dementia: float
  search_trends_dentin_hypersensitivity: float
  search_trends_depersonalization: float
  search_trends_depression: float
  search_trends_dermatitis: float
  search_trends_desquamation: float
  search_trends_developmental_disability: float
  search_trends_diabetes: float
  search_trends_diabetic_ketoacidosis: float
  search_trends_diarrhea: float
  search_trends_dizziness: float
  search_trends_dry_eye_syndrome: float
  search_trends_dysautonomia: float
  search_trends_dysgeusia: float
  search_trends_dysmenorrhea: float
  search_trends_dyspareunia: float
  search_trends_dysphagia: float
  search_trends_dysphoria: float
  search_trends_dystonia: float
  search_trends_dysuria: float
  search_trends_ear_pain: float
  search_trends_eczema: float
  search_trends_edema: float
  search_trends_encephalitis: float
  search_trends_encephalopathy: float
  search_trends_epidermoid_cyst: float
  search_trends_epilepsy: float
  search_trends_epiphora: float
  search_trends_erectile_dysfunction: float
  search_trends_erythema: float
  search_trends_erythema_chronicum_migrans: float
  search_trends_esophagitis: float
  search_trends_excessive_daytime_sleepiness: float
  search_trends_eye_pain: float
  search_trends_eye_strain: float
  search_trends_facial_nerve_paralysis: float
  search_trends_facial_swelling: float
  search_trends_fasciculation: float
  search_trends_fatigue: float
  search_trends_fatty_liver_disease: float
  search_trends_fecal_incontinence: float
  search_trends_fever: float
  search_trends_fibrillation: float
  search_trends_fibrocystic_breast_changes: float
  search_trends_fibromyalgia: float
  search_trends_flatulence: float
  search_trends_floater: float
  search_trends_focal_seizure: float
  search_trends_folate_deficiency: float
  search_trends_food_craving: float
  search_trends_food_intolerance: float
  search_trends_frequent_urination: float
  search_trends_gastroesophageal_reflux_disease: float
  search_trends_gastroparesis: float
  search_trends_generalized_anxiety_disorder: float
  search_trends_generalized_tonicâ€“clonic_seizure: float
  search_trends_genital_wart: float
  search_trends_gingival_recession: float
  search_trends_gingivitis: float
  search_trends_globus_pharyngis: float
  search_trends_goitre: float
  search_trends_gout: float
  search_trends_grandiosity: float
  search_trends_granuloma: float
  search_trends_guilt: float
  search_trends_hair_loss: float
  search_trends_halitosis: float
  search_trends_hay_fever: float
  search_trends_headache: float
  search_trends_heart_arrhythmia: float
  search_trends_heart_murmur: float
  search_trends_heartburn: float
  search_trends_hematochezia: float
  search_trends_hematoma: float
  search_trends_hematuria: float
  search_trends_hemolysis: float
  search_trends_hemoptysis: float
  search_trends_hemorrhoids: float
  search_trends_hepatic_encephalopathy: float
  search_trends_hepatitis: float
  search_trends_hepatotoxicity: float
  search_trends_hiccup: float
  search_trends_hip_pain: float
  search_trends_hives: float
  search_trends_hot_flash: float
  search_trends_hydrocephalus: float
  search_trends_hypercalcaemia: float
  search_trends_hypercapnia: float
  search_trends_hypercholesterolemia: float
  search_trends_hyperemesis_gravidarum: float
  search_trends_hyperglycemia: float
  search_trends_hyperhidrosis: float
  search_trends_hyperkalemia: float
  search_trends_hyperlipidemia: float
  search_trends_hypermobility: float
  search_trends_hyperpigmentation: float
  search_trends_hypersomnia: float
  search_trends_hypertension: float
  search_trends_hyperthermia: float
  search_trends_hyperthyroidism: float
  search_trends_hypertriglyceridemia: float
  search_trends_hypertrophy: float
  search_trends_hyperventilation: float
  search_trends_hypocalcaemia: float
  search_trends_hypochondriasis: float
  search_trends_hypoglycemia: float
  search_trends_hypogonadism: float
  search_trends_hypokalemia: float
  search_trends_hypomania: float
  search_trends_hyponatremia: float
  search_trends_hypotension: float
  search_trends_hypothyroidism: float
  search_trends_hypoxemia: float
  search_trends_hypoxia: float
  search_trends_impetigo: float
  search_trends_implantation_bleeding: float
  search_trends_impulsivity: float
  search_trends_indigestion: float
  search_trends_infection: float
  search_trends_inflammation: float
  search_trends_inflammatory_bowel_disease: float
  search_trends_ingrown_hair: float
  search_trends_insomnia: float
  search_trends_insulin_resistance: float
  search_trends_intermenstrual_bleeding: float
  search_trends_intracranial_pressure: float
  search_trends_iron_deficiency: float
  search_trends_irregular_menstruation: float
  search_trends_itch: float
  search_trends_jaundice: float
  search_trends_kidney_failure: float
  search_trends_kidney_stone: float
  search_trends_knee_pain: float
  search_trends_kyphosis: float
  search_trends_lactose_intolerance: float
  search_trends_laryngitis: float
  search_trends_leg_cramps: float
  search_trends_lesion: float
  search_trends_leukorrhea: float
  search_trends_lightheadedness: float
  search_trends_low_back_pain: float
  search_trends_low-grade_fever: float
  search_trends_lymphedema: float
  search_trends_major_depressive_disorder: float
  search_trends_malabsorption: float
  search_trends_male_infertility: float
  search_trends_manic_disorder: float
  search_trends_melasma: float
  search_trends_melena: float
  search_trends_meningitis: float
  search_trends_menorrhagia: float
  search_trends_middle_back_pain: float
  search_trends_migraine: float
  search_trends_milium: float
  search_trends_mitral_insufficiency: float
  search_trends_mood_disorder: float
  search_trends_mood_swing: float
  search_trends_morning_sickness: float
  search_trends_motion_sickness: float
  search_trends_mouth_ulcer: float
  search_trends_muscle_atrophy: float
  search_trends_muscle_weakness: float
  search_trends_myalgia: float
  search_trends_mydriasis: float
  search_trends_myocardial_infarction: float
  search_trends_myoclonus: float
  search_trends_nasal_congestion: float
  search_trends_nasal_polyp: float
  search_trends_nausea: float
  search_trends_neck_mass: float
  search_trends_neck_pain: float
  search_trends_neonatal_jaundice: float
  search_trends_nerve_injury: float
  search_trends_neuralgia: float
  search_trends_neutropenia: float
  search_trends_night_sweats: float
  search_trends_night_terror: float
  search_trends_nocturnal_enuresis: float
  search_trends_nodule: float
  search_trends_nosebleed: float
  search_trends_nystagmus: float
  search_trends_obesity: float
  search_trends_onychorrhexis: float
  search_trends_oral_candidiasis: float
  search_trends_orthostatic_hypotension: float
  search_trends_osteopenia: float
  search_trends_osteophyte: float
  search_trends_osteoporosis: float
  search_trends_otitis: float
  search_trends_otitis_externa: float
  search_trends_otitis_media: float
  search_trends_pain: float
  search_trends_palpitations: float
  search_trends_pancreatitis: float
  search_trends_panic_attack: float
  search_trends_papule: float
  search_trends_paranoia: float
  search_trends_paresthesia: float
  search_trends_pelvic_inflammatory_disease: float
  search_trends_pericarditis: float
  search_trends_periodontal_disease: float
  search_trends_periorbital_puffiness: float
  search_trends_peripheral_neuropathy: float
  search_trends_perspiration: float
  search_trends_petechia: float
  search_trends_phlegm: float
  search_trends_photodermatitis: float
  search_trends_photophobia: float
  search_trends_photopsia: float
  search_trends_pleural_effusion: float
  search_trends_pleurisy: float
  search_trends_pneumonia: float
  search_trends_podalgia: float
  search_trends_polycythemia: float
  search_trends_polydipsia: float
  search_trends_polyneuropathy: float
  search_trends_polyuria: float
  search_trends_poor_posture: float
  search_trends_post-nasal_drip: float
  search_trends_postural_orthostatic_tachycardia_syndrome: float
  search_trends_prediabetes: float
  search_trends_proteinuria: float
  search_trends_pruritus_ani: float
  search_trends_psychosis: float
  search_trends_ptosis: float
  search_trends_pulmonary_edema: float
  search_trends_pulmonary_hypertension: float
  search_trends_purpura: float
  search_trends_pus: float
  search_trends_pyelonephritis: float
  search_trends_radiculopathy: float
  search_trends_rectal_pain: float
  search_trends_rectal_prolapse: float
  search_trends_red_eye: float
  search_trends_renal_colic: float
  search_trends_restless_legs_syndrome: float
  search_trends_rheum: float
  search_trends_rhinitis: float
  search_trends_rhinorrhea: float
  search_trends_rosacea: float
  search_trends_round_ligament_pain: float
  search_trends_rumination: float
  search_trends_scar: float
  search_trends_sciatica: float
  search_trends_scoliosis: float
  search_trends_seborrheic_dermatitis: float
  search_trends_self-harm: float
  search_trends_sensitivity_to_sound: float
  search_trends_sexual_dysfunction: float
  search_trends_shallow_breathing: float
  search_trends_sharp_pain: float
  search_trends_shivering: float
  search_trends_shortness_of_breath: float
  search_trends_shyness: float
  search_trends_sinusitis: float
  search_trends_skin_condition: float
  search_trends_skin_rash: float
  search_trends_skin_tag: float
  search_trends_skin_ulcer: float
  search_trends_sleep_apnea: float
  search_trends_sleep_deprivation: float
  search_trends_sleep_disorder: float
  search_trends_snoring: float
  search_trends_sore_throat: float
  search_trends_spasticity: float
  search_trends_splenomegaly: float
  search_trends_sputum: float
  search_trends_stomach_rumble: float
  search_trends_strabismus: float
  search_trends_stretch_marks: float
  search_trends_stridor: float
  search_trends_stroke: float
  search_trends_stuttering: float
  search_trends_subdural_hematoma: float
  search_trends_suicidal_ideation: float
  search_trends_swelling: float
  search_trends_swollen_feet: float
  search_trends_swollen_lymph_nodes: float
  search_trends_syncope: float
  search_trends_tachycardia: float
  search_trends_tachypnea: float
  search_trends_telangiectasia: float
  search_trends_tenderness: float
  search_trends_testicular_pain: float
  search_trends_throat_irritation: float
  search_trends_thrombocytopenia: float
  search_trends_thyroid_nodule: float
  search_trends_tic: float
  search_trends_tinnitus: float
  search_trends_tonsillitis: float
  search_trends_toothache: float
  search_trends_tremor: float
  search_trends_trichoptilosis: float
  search_trends_tumor: float
  search_trends_type_2_diabetes: float
  search_trends_unconsciousness: float
  search_trends_underweight: float
  search_trends_upper_respiratory_tract_infection: float
  search_trends_urethritis: float
  search_trends_urinary_incontinence: float
  search_trends_urinary_tract_infection: float
  search_trends_urinary_urgency: float
  search_trends_uterine_contraction: float
  search_trends_vaginal_bleeding: float
  search_trends_vaginal_discharge: float
  search_trends_vaginitis: float
  search_trends_varicose_veins: float
  search_trends_vasculitis: float
  search_trends_ventricular_fibrillation: float
  search_trends_ventricular_tachycardia: float
  search_trends_vertigo: float
  search_trends_viral_pneumonia: float
  search_trends_visual_acuity: float
  search_trends_vomiting: float
  search_trends_wart: float
  search_trends_water_retention: float
  search_trends_weakness: float
  search_trends_weight_gain: float
  search_trends_wheeze: float
  search_trends_xeroderma: float
  search_trends_xerostomia: float
  search_trends_yawn: float

auxiliary:
  metadata: ./data/metadata.csv
  localities: ./data/localities.csv
  country_codes: ./data/country_codes.csv
  knowledge_graph: ./data/knowledge_graph.csv

sources:

  # - name: pipelines._common.google_search_trends.GoogleSearchTrendsL1DataSource
  #   fetch:
  #     - url: "https://raw.githubusercontent.com/google-research/open-covid-19-data/master/data/inputs/downloaded/search_trends_symptoms_dataset/2020-08-30/United%20States%20of%20America/2020_US_daily_symptoms_dataset.csv"
  #   parse:
  #     low_memory: false
  #   test:
  #     # Skip because it's too slow
  #     skip: true

  - name: pipelines._common.google_search_trends.GoogleSearchTrendsL2DataSource
    fetch:
      - url: "https://raw.github.com/google-research/open-covid-19-data/master/data/inputs/downloaded/search_trends_symptoms_dataset/2020-08-30/United%20States%20of%20America/subregions/{subregion1_name_path}/2020_US_{subregion1_name_file}_daily_symptoms_dataset.csv"
    parse:
      low_memory: false
    test:
      # Skip because it's too slow
      skip: true
    automation:
      # Run only twice a day, since it's so resource consuming
      schedule: "0 */12 * * *"
      # Run in a separate preemptible VM
      deferred: true
