# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Index pipeline configuration

schema:
  key: str
  wikidata: str
  datacommons: str
  country_code: str
  country_name: str
  subregion1_code: str
  subregion1_name: str
  subregion2_code: str
  subregion2_name: str
  3166-1-alpha-2: str
  3166-1-alpha-3: str
  aggregation_level: int

auxiliary:
  metadata: ./src/data/metadata.csv
  country_codes: ./src/data/country_codes.csv
  knowledge_graph: ./src/data/knowledge_graph.csv

sources:
  - name: pipelines.index.index.IndexDataSource
