# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

schema:
  date: str
  key: str
  new_persons_vaccinated: int
  total_persons_vaccinated: int
  new_persons_fully_vaccinated: int
  total_persons_fully_vaccinated: int
  new_vaccine_doses_administered: int
  total_vaccine_doses_administered: int
  new_persons_vaccinated_pfizer: int
  total_persons_vaccinated_pfizer: int
  new_persons_fully_vaccinated_pfizer: int
  total_persons_fully_vaccinated_pfizer: int
  new_vaccine_doses_administered_pfizer: int
  total_vaccine_doses_administered_pfizer: int
  new_persons_vaccinated_moderna: int
  total_persons_vaccinated_moderna: int
  new_persons_fully_vaccinated_moderna: int
  total_persons_fully_vaccinated_moderna: int
  new_vaccine_doses_administered_moderna: int
  total_vaccine_doses_administered_moderna: int
  new_persons_vaccinated_janssen: int
  total_persons_vaccinated_janssen: int
  new_persons_fully_vaccinated_janssen: int
  total_persons_fully_vaccinated_janssen: int
  new_vaccine_doses_administered_janssen: int
  total_vaccine_doses_administered_janssen: int


auxiliary:
  metadata: ./data/metadata.csv
  localities: ./data/localities.csv
  country_codes: ./data/country_codes.csv
  knowledge_graph: ./data/knowledge_graph.csv

sources:

  # Data sources for all countries level 0
  - class: pipelines.vaccinations.xx_owid.OurWorldInDataSource
    label: Our World In Data
    fetch:
      - url: "https://github.com/owid/covid-19-data/raw/master/public/data/vaccinations/vaccinations.csv"
    test:
      location_key_match: '^..$'

  # Data sources for AR levels 0 + 1
  - class: pipelines.vaccinations.ar_authority.ArgentinaDataSource
    label: Datos Argentina
    fetch:
      - url: "https://sisa.msal.gov.ar/datos/descargas/covid-19/files/datos_nomivac_covid19.zip"
    test:
      # Skip because it's too slow
      skip: true
      location_key_match:
        - '^AR$'
        - '^AR_[^_]+$'
        - '^AR_[^_]+_[^_]+$'

  # Data sources for AU levels 0 + 1
  - class: pipelines.epidemiology.au_covidlive.AustraliaCovidLiveDataSource
    label: covidlive.com.au
    website: https://covidlive.com.au
    license: CC-BY
    license_url: https://covidlive.com.au
    fetch:
      - url: "https://covidlive.com.au/covid-live.csv"
    test:
      location_key_match:
        - '^AU$'
        - '^AU_[^_]+$'

  # Data sources for AT levels 0 + 1
  - class: pipelines.vaccinations.at_authority.AustriaDataSource
    label: Open Data Ã–sterreich
    website: https://www.data.gv.at/katalog/dataset/4312623f-2cdc-4a59-bea5-877310e6e48d
    fetch:
      - url: "https://info.gesundheitsministerium.gv.at/data/timeline-eimpfpass.csv"
    parse:
      sep: ";"
    test:
      location_key_match: '^AT_[^_]+$'

  # Data sources for BE levels 0 + 1
  - class: pipelines.vaccinations.be_covid_vaccinatie.BelgiumDataSource
    label: covid-vaccinatie.be
    fetch:
      - url: "https://covid-vaccinatie.be/api/v1/administered.csv"
    test:
      location_key_match:
        - '^BE$'
        - '^BE_[^_]+$'

  # Data sources for BG levels 0 + 1
  - class: pipelines.vaccinations.bg_finmango.FinMangoBulgariaDataSource
    label: Ministry of Health of Bulgaria (via FinMango)
    fetch:
      - url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vT3xzDXa5yd1lQZVrqNNFRy_4rj6Ie-YC5tpdOFlFYH4Qj_z5s1WPbsapfx6oPITw6uke_LUo7OCA2E/pub?gid=0&single=true&output=csv"
        opts:
          ext: csv
    test:
      location_key_match:
        - '^BG$'
        - '^BG_[^_]+$'

  # Data sources for BO levels 0 + 1
  - class: pipelines.vaccinations.bo_finmango.FinMangoBoliviaDataSource
    label: Ministry of Health of Bolivia (via FinMango)
    fetch:
      - url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vTQPaCIPwOdo-ELdSPlRSlLWqB0X3PtpZJdB1aEIjdo_HBW2qAe_9bY6rE3t_AMakUPNk2TPuwzPKx_/pub?gid=0&single=true&output=csv"
        opts:
          ext: csv
      - url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vTQPaCIPwOdo-ELdSPlRSlLWqB0X3PtpZJdB1aEIjdo_HBW2qAe_9bY6rE3t_AMakUPNk2TPuwzPKx_/pub?gid=349214778&single=true&output=csv"
        opts:
          ext: csv
    aggregate:
      subregion1: ["total_persons_vaccinated", "total_persons_fully_vaccinated", "total_vaccine_doses_administered"]
    test:
      location_key_match:
        - '^BO$'
        - '^BO_[^_]+$'

  # Data sources for BR levels 0 + 1 + 2

  # Even though this is an authoritative data source, it has significant delays in the data so we
  # deprioritize it with respect to the crowd-sourced data source
  - class: pipelines.vaccinations.br_authority.BrazilDataSource
    label: Brazil Ministry of Health (openDataSUS)
    fetch:
      - url: "https://s3-sa-east-1.amazonaws.com/ckan.saude.gov.br/PNI/vacina/uf/{date}/uf%3D{subregion1_code}/part-00000-9bf0f6da-b13b-4025-9160-2dd9b163f3f3.c000.csv"
        opts:
          date_format: '%Y-%m-%d'
    parse:
      sep: ";"
    test:
      # Skip unit testing because it's very slow
      skip: true
      location_key_match:
        - '^BR$'
        - '^BR_[^_]+$'
        - '^BR_[^_]+_[^_]+$'
    automation:
      # Run only twice a day, since it's so resource consuming
      schedule: "0 */12 * * *"
      # Run in a separate job group because it's prone to failure
      job_group: opendatasus

  - class: pipelines.vaccinations.br_covid19br.Covid19BrDataSource
    label: coronavirusbra1.github.io (via @wcota/covid19br)
    website: https://coronavirusbra1.github.io/
    license: CC-BY
    license_url: https://github.com/wcota/covid19br/blob/6e994b0fef2056e31364bfa2e69c5d61060f0ccf/DESCRIPTION.en.md#by-federative-units-cases-brazil-totalcsv-and-cases-brazil-statescsv
    fetch:
      - url: "https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-states.csv"
        opts:
          ext: csv
    test:
      location_key_match:
        - '^BR$'
        - '^BR_[^_]+$'

  # Data sources for CA levels 0 + 1
  - class: pipelines.vaccinations.ca_authority.CanadaDataSource
    label: Canada Ministry of Health
    fetch:
      - url: "https://health-infobase.canada.ca/src/data/covidLive/vaccination-coverage-map.csv"
    test:
      location_key_match:
        - '^CA$'
        - '^CA_[^_]+$'

  # Data sources for CH levels 0 + 1
  - class: pipelines.vaccinations.ch_authority.SwitzerlandPersonsDataSource
    label: Switzerland Ministry of Health
    website: https://www.covid19.admin.ch
    fetch:
      - url: "https://www.covid19.admin.ch/api/data/context"
    test:
      location_key_match:
        - '^CH$'
        - '^LI$'
        - '^CH_[^_]+$'

  - class: pipelines.vaccinations.ch_authority.SwitzerlandDosesDataSource
    label: Switzerland Ministry of Health
    website: https://www.covid19.admin.ch
    fetch:
      - url: "https://www.covid19.admin.ch/api/data/context"
    test:
      location_key_match:
        - '^CH$'
        - '^LI$'
        - '^CH_[^_]+$'

  # Data sources for CO level 1
  - class: pipelines.vaccinations.co_finmango.FinMangoColombiaDataSource
    label: Colombia Ministry of Health (via FinMango)
    fetch:
      - url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vSKtYZV5XRCjVH8TWOLh8paDQOA0aK7yYnMVlpXqoTfdZ71daNG9260evPjnW0th9uOIqRntn0rHFgn/pub?gid=0&single=true&output=csv"
        opts:
          ext: csv
    test:
      # Country-level data not reported because data source is incomplete
      location_key_match: '^CO_[^_]+$'

  # Data sources for CZ levels 0 + 1
  - class: pipelines.vaccinations.cz_authority.CzechRepublicDataSource
    label: Czech Republic Ministry of Health
    fetch:
      - url: "https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/ockovani.csv"
    aggregate:
      subregion1: ["total_persons_vaccinated", "total_persons_fully_vaccinated", "total_vaccine_doses_administered"]
    test:
      location_key_match:
        - '^CZ$'
        - '^CZ_[^_]+$'

  # Data sources for DE levels 0 + 1
  - class: pipelines.vaccinations.de_finmango.FinMangoGermanyDataSource
    label: Robert Koch Institute (via FinMango)
    fetch:
      - url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vQBlleeDihfdTZLuDIczEsmKy0Ql-YOYUfBTy3NKxyNbTR1IRd7EbIp5cPS0PVzgOxn-zCWTY4ZVm_5/pub?output=xlsx"
        opts:
          ext: xlsx
    parse:
      sheet_name: ['automated1', 'automated2', 'automated3']
    test:
      location_key_match:
        - '^DE$'
        - '^DE_[^_]+$'

  # Data sources for ES levels 0 + 1
  - class: pipelines.vaccinations.es_authority.SpainDataSource
    label: Spain Ministry of Health
    fetch:
      - url: "https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov/documentos/Informe_Comunicacion_{date}.ods"
        opts:
          ignore_failure: true
    test:
      location_key_match:
        - '^ES$'
        - '^ES_[^_]+$'

  # Data sources for FR levels 0 + 1 + 2
  - class: pipelines.vaccinations.fr_authority.FranceDepartmentDataSource
    label: data.gouv.fr
    fetch:
      - url: "https://www.data.gouv.fr/fr/datasets/r/4f39ec91-80d7-4602-befb-4b522804c0af"
        opts:
          ext: csv
    parse:
      sep: ';'
    test:
      location_key_match:
        - '^FR_[^_]+_[^_]+$'
  - class: pipelines.vaccinations.fr_authority.FranceRegionDataSource
    label: data.gouv.fr
    fetch:
      - url: "https://www.data.gouv.fr/fr/datasets/r/735b0df8-51b4-4dd2-8a2d-8e46d77d60d8"
        opts:
          ext: csv
    parse:
      sep: ';'
    test:
      location_key_match:
        - '^FR_[^_]+$'

  - class: pipelines.vaccinations.fr_authority.FranceCountryDataSource
    label: data.gouv.fr
    fetch:
      - url: "https://www.data.gouv.fr/fr/datasets/r/efe23314-67c4-45d3-89a2-3faef82fae90"
        opts:
          ext: csv
    parse:
      sep: ';'
    test:
      location_key_match:
        - '^FR$'

  # Data sources for GB levels 0 + 1
  - class: pipelines.vaccinations.gb_finmango.FinMangoUkDataSource
    label: National Health Service (via FinMango)
    fetch:
      - url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vRbXZEVtSWDL8jc66A0BOnQuLSzNF_yaGF7RWpkOYZRHPwnWGs5Fh6RxrDnBFKribuo9gm71lBlJnEL/pub?gid=0&single=true&output=csv"
        opts:
          ext: csv
    test:
      location_key_match:
        - '^GB_ENG$'
        - '^GB_UK.$'

  - class: pipelines.vaccinations.gb_authority.GreatBritainDataSource
    label: National Health Service
    fetch:
      - url: "https://api.coronavirus.data.gov.uk/v2/data?areaType=nation&metric=cumPeopleVaccinatedFirstDoseByPublishDate&metric=cumPeopleVaccinatedSecondDoseByPublishDate&format=csv"
        opts:
          ext: csv
    parse:
      level: nation
    test:
      location_key_match:
        - '^GB_ENG$'
        - '^GB_NIR$'
        - '^GB_SCT$'
        - '^GB_WLS$'

  - class: pipelines.vaccinations.gb_authority.GreatBritainDataSource
    label: National Health Service
    fetch:
      - url: "https://api.coronavirus.data.gov.uk/v2/data?areaType=overview&metric=cumPeopleVaccinatedFirstDoseByPublishDate&metric=cumPeopleVaccinatedSecondDoseByPublishDate&format=csv"
        opts:
          ext: csv
    parse:
      level: country
    test:
      location_key_match: '^GB$'

  - class: pipelines.vaccinations.in_covid19india_org.Covid19IndiaOrgL1DataSource
    label: covid19india.org
    fetch:
      - url: "http://data.covid19india.org/csv/latest/vaccine_doses_statewise_v2.csv"
    # No need to aggregate since country-level sources appear to be more accurate
    # aggregate:
    #   subregion1: ["total_persons_vaccinated", "total_persons_fully_vaccinated", "total_vaccine_doses_administered"]
    test:
      location_key_match: '^IN_[^_]+$'

  # Data sources for IT levels 0 + 1
  - class: pipelines.vaccinations.it_authority.ItalyDataSource
    label: Italy Ministry of Health
    fetch:
      - url: "https://raw.githubusercontent.com/italia/covid19-opendata-vaccini/master/dati/somministrazioni-vaccini-summary-latest.csv"
    test:
      location_key_match:
        - '^IT$'
        - '^IT_[^_]+$'

  # Data sources for IL levels 2 (we aggregated to L1)
  - class: pipelines.epidemiology.il_authority.IsraelDataSource
    label: Israel Ministry of Health
    fetch:
      - url: "https://data.gov.il/api/3/action/datastore_search?resource_id=d07c0771-01a8-43b2-96cc-c6154e7fa9bd"
    test:
      location_key_match:
        - '^IL$'
        - '^IL_[^_]+$'
        - '^IL_[^_]+_[^_]+$'

  # Data sources for SE level 0 + 1
  - class: pipelines.vaccinations.se_authority.SwedenDataSource
    label: Sweden Ministry of Health
    fetch:
      - url: "https://fohm.maps.arcgis.com/sharing/rest/content/items/fc749115877443d29c2a49ea9eca77e9/data"
        opts:
          ext: xlsx
    parse:
      sheet_name: "Vaccinerade tidsserie"
    # OWID reports daily data, but this source is only weekly
    query: key != "SE"
    test:
      location_key_match:
        # - '^SE$'
        - '^SE_[^_]+$'

  # Data sources for SI levels 0 + 1
  - class: pipelines.vaccinations.si_finmango.FinMangoSloveniaDataSource
    label: Slovenia Ministry of Health (via FinMango)
    fetch:
      - url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vSVlVRyQwhlSZpwAAh5ARpDr4rNFmPrDXQ0_8jrcMWfJ734grINta10mrHGXygPXZaMkIepN8QUe3aA/pub?gid=0&single=true&output=csv"
        opts:
          ext: csv
    test:
      location_key_match:
        - '^SI$'
        - '^SI_[^_]+$'

  # Data sources for SK level 0 + 1
  - class: pipelines.vaccinations.sk_authority.SlovakiaDataSource
    label: korona.gov.sk
    fetch:
      - name: "regions"
        url: "https://data.korona.gov.sk/api/regions"
      - name: "vaccine_by_regions"
        url: "https://data.korona.gov.sk/api/vaccinations/by-region"
    aggregate:
      subregion1: ["new_persons_vaccinated", "new_persons_fully_vaccinated", "new_vaccine_doses_administered", "total_persons_vaccinated", "total_persons_fully_vaccinated", "total_vaccine_doses_administered"]
    test:
      location_key_match:
        - '^SK$'
        - '^SK_[^_]+$'

  # Data sources for US level 2
  - class: pipelines.vaccinations.us_authority_cached.USCountyCachedDataSource
    label: Centers for Disease Control and Prevention
    # No URL is given because it uses the cache
    fetch:
      - cache_key: US_CDC_counties_vaccinations
    test:
      location_key_match:
        - '^US_[^_]+_[^_]+$'

  # Data sources for US level 1
  - class: pipelines.vaccinations.xx_owid.OurWorldInDataUSDataSource
    label: Our World In Data
    fetch:
      - url: "https://github.com/owid/covid-19-data/raw/master/public/data/vaccinations/us_state_vaccinations.csv"
    test:
      location_key_match: '^US_[^_]+$'

  # Data sources for US level 0 and 1
  - class: pipelines.vaccinations.us_authority_vaccination_type.CDCCachedDataSourceVaccinationType
    label: Centers for Disease Control and Prevention
    # No URL is given because it uses the cache
    fetch:
      - cache_key: US_CDC_states_vaccinations
    test:
      location_key_match:
        -  '^US$'
        -  '^US_[^_]+$'

  # Data sources for US level 0
  - class: pipelines.vaccinations.us_authority.CDCDataSource
    label: Centers for Disease Control and Prevention
    fetch:
      - url: "https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_trends_data"
        name: vaccination_trends_data
        opts:
          ext: json
    test:
      location_key_match: '^US$'
